// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDQiP_y3IKk5bh_m1x3ri0RX4sLxCCt1I',
    appId: '1:110425275736:web:b7a254ad62fb521d3b792d',
    messagingSenderId: '110425275736',
    projectId: 'ohana-cares',
    authDomain: 'ohana-cares.firebaseapp.com',
    storageBucket: 'ohana-cares.appspot.com',
    measurementId: 'G-EW9CFZ27NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZt8AgEB7g1XhG88sRvx9tWCT99mFlPAk',
    appId: '1:110425275736:android:5529f06f5bde72d03b792d',
    messagingSenderId: '110425275736',
    projectId: 'ohana-cares',
    storageBucket: 'ohana-cares.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfD_xj3jsTCoSRl8Ypf440bLsybqELF1U',
    appId: '1:110425275736:ios:bb69e1d2a59497733b792d',
    messagingSenderId: '110425275736',
    projectId: 'ohana-cares',
    storageBucket: 'ohana-cares.appspot.com',
    iosClientId: '110425275736-73gcu8ok6o7gkb39hr2hm6pg30lssi4g.apps.googleusercontent.com',
    iosBundleId: 'com.kitahack.ohanaCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfD_xj3jsTCoSRl8Ypf440bLsybqELF1U',
    appId: '1:110425275736:ios:bb69e1d2a59497733b792d',
    messagingSenderId: '110425275736',
    projectId: 'ohana-cares',
    storageBucket: 'ohana-cares.appspot.com',
    iosClientId: '110425275736-73gcu8ok6o7gkb39hr2hm6pg30lssi4g.apps.googleusercontent.com',
    iosBundleId: 'com.kitahack.ohanaCare',
  );
}
